- name: Automate Creation of Another IKE Gateway on Palo Alto 
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "192.168.65.120"
      username: "admin"
      password: "admin"
      port: 443

    ike_version_2: "ikev1"  # Version IKE fixée

  vars_prompt:
    - name: ike_gateway_name_input
      prompt: "Enter the IKE Gateway name"
      private: no

    - name: local_ip_input
      prompt: "Enter the Local IP address"
      private: no

    - name: peer_ip_input
      prompt: "Enter the Peer IP address"
      private: no

    - name: pre_shared_key_input
      prompt: "Enter the Pre-Shared Key"
      private: yes

  tasks:
    - name: Set values based on environment or prompt
      set_fact:
        ike_gateway_name_2: "{{ ike_gateway_name_2 | default(ike_gateway_name_input) }}"
        local_ip_2: "{{ local_ip_2 | default(local_ip_input) }}"
        peer_ip_2: "{{ peer_ip_2 | default(peer_ip_input) }}"
        pre_shared_key_2: "{{ pre_shared_key_2 | default(pre_shared_key_input) }}"

    - name: Create the second IKE Gateway
      panos_ike_gateway:
        provider: "{{ palo_provider }}"
        name: "{{ ike_gateway_name_2 }}"
        interface: "vlan.1"
        local_ip_address: "{{ local_ip_2 }}"
        peer_ip_value: "{{ peer_ip_2 }}"
        pre_shared_key: "{{ pre_shared_key_2 }}"
        version: "{{ ike_version_2 }}"
      register: ike_gateway_creation_2

    - name: Display IKE Gateway 2 creation result
      debug:
        msg: "Second IKE Gateway {{ ike_gateway_name_2 }} creation result: {{ ike_gateway_creation_2 }}"
