- name: Automate Loopback Interface Creation on Palo Alto
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "192.168.65.120"
      username: "admin"
      password: "admin"
      port: 443

  vars_prompt:
    - name: interface_name_input
      prompt: "Enter the name of the loopback interface (e.g. loopback.3)"
      private: no

    - name: interface_ip_input
      prompt: "Enter the IP address with CIDR (e.g. 192.168.200.1/32)"
      private: no

  tasks:
    - name: Set interface variables from environment or prompt
      set_fact:
        interface_name: "{{ interface_name | default(interface_name_input) }}"
        interface_ip: "{{ interface_ip | default(interface_ip_input) }}"

    - name: Create Loopback Interface
      paloaltonetworks.panos.panos_loopback_interface:
        provider: "{{ palo_provider }}"
        if_name: "{{ interface_name }}"
        ip: ["{{ interface_ip }}"]
        comment: "Created via Ansible"
        state: "present"
      register: loopback_result

    - name: Show result
      debug:
        msg: "Loopback interface {{ interface_name }} creation result: {{ loopback_result }}"
