- name: Automate Assignment of Security Profiles to a Rule on Palo Alto
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  vars_prompt:
    - name: rule_name
      prompt: "Enter rule name (e.g. Allow-Web-Traffic)"
      private: no

    - name: source_zone
      prompt: "Enter source zone(s), comma-separated (e.g. Trust)"
      private: no

    - name: destination_zone
      prompt: "Enter destination zone(s), comma-separated (e.g. Untrust)"
      private: no

    - name: source_ip
      prompt: "Enter source IP(s), comma-separated (e.g. any)"
      private: no

    - name: destination_ip
      prompt: "Enter destination IP(s), comma-separated (e.g. any)"
      private: no

    - name: application
      prompt: "Enter application(s), comma-separated (e.g. web-browsing)"
      private: no

    - name: service
      prompt: "Enter service (e.g. application-default)"
      private: no

    - name: action
      prompt: "Enter action (allow, deny, drop, etc.)"
      private: no

    - name: antivirus
      prompt: "Enter Antivirus profile name (e.g. default)"
      private: no

    - name: spyware
      prompt: "Enter Spyware profile name (e.g. default)"
      private: no

    - name: vulnerability
      prompt: "Enter Vulnerability profile name (e.g. default)"
      private: no

    - name: url_filtering
      prompt: "Enter URL Filtering profile name (e.g. default)"
      private: no

  vars:
    palo_provider:
      ip_address: "192.168.65.120"
      username: "admin"
      password: "admin"
      port: 443

  tasks:
    - name: Add security profiles to rule
      panos_security_rule:
        provider: "{{ palo_provider }}"
        rule_name: "{{ rule_name }}"
        source_zone: "{{ source_zone.split(',') }}"
        destination_zone: "{{ destination_zone.split(',') }}"
        source_ip: "{{ source_ip.split(',') }}"
        destination_ip: "{{ destination_ip.split(',') }}"
        application: "{{ application.split(',') }}"
        service: "{{ service }}"
        action: "{{ action }}"
        antivirus: "{{ antivirus }}"
        spyware: "{{ spyware }}"
        vulnerability: "{{ vulnerability }}"
        url_filtering: "{{ url_filtering }}"
        state: present
      register: profile_rule_result

    - name: Show result of security profile update
      debug:
        var: profile_rule_result
