- name: Automate Static Route Configuration on Palo Alto
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "192.168.65.120"   # IP fixée ici
      username: "admin"              # Nom d'utilisateur fixé ici
      password: "admin"              # Mot de passe fixé ici
      port: 443

  vars_prompt:
    - name: "static_route_name"
      prompt: "Enter the name of the static route: (e.g. StaticRouteToNetworkpalo4)"
      private: no

    - name: "destination_network"
      prompt: "Enter the destination network: (e.g. 10.1.7.0/24)"
      private: no

    - name: "interface"
      prompt: "Enter the interface: (e.g. tunnel.1)"
      private: no

    - name: "next_hop_ip"
      prompt: "Enter the next-hop IP address: (e.g. 10.1.7.4)"
      private: no

    - name: "admin_dist"
      prompt: "Enter the administrative distance: (default 10)"
      private: no
      default: "10"

    - name: "metric"
      prompt: "Enter the metric: (default 10)"
      private: no
      default: "10"

  tasks:
    - name: Create the Static Route
      panos_static_route:
        provider: "{{ palo_provider }}"
        name: "{{ static_route_name }}"
        destination: "{{ destination_network }}"
        interface: "{{ interface }}"
        nexthop: "{{ next_hop_ip }}"
        admin_dist: "{{ admin_dist }}"
        metric: "{{ metric }}"
        state: "present"
      register: static_route_creation

    - name: Display Static Route creation result
      debug:
        msg: "Static Route {{ static_route_name }} creation result: {{ static_route_creation }}"
