- name: Automate Creation of a Security Zone on Palo Alto
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos

  vars:
    palo_provider:
      ip_address: "192.168.65.120"
      username: "admin"
      password: "admin"
      port: 443

    
    zone_name_input: "Trust"
    interface_list_input: "loopback"
    include_list_input: "192.168.1.0/24"
    exclude_list_input: "192.168.1.100,192.168.1.101"

  tasks:
    - name: Parse interfaces from comma-separated input
      set_fact:
        interface_list: "{{ interface_list_input.split(',') }}"

    - name: Parse include list
      set_fact:
        include_list: "{{ include_list_input.split(',') }}"

    - name: Parse exclude list
      set_fact:
        exclude_list: "{{ exclude_list_input.split(',') }}"

    - name: Create Security Zone
      panos_zone:
        provider: "{{ palo_provider }}"
        zone: "{{ zone_name_input }}"
        mode: "layer3"
        interface: "{{ interface_list }}"
        enable_userid: true 
        include_acl: "{{ include_list }}"
        exclude_acl: "{{ exclude_list }}"
      register: zone_creation

    - name: Show result
      debug:
        msg: "Zone {{ zone_name_input }} creation result: {{ zone_creation }}"
